language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-24
    
branches:
  only:
    - master
    - travis
    
before_script: 
    - cd demo/demo

script: 
    - ./gradlew build --stacktrace
